CI: macos is very bad on GitHub actions. Do 3 attempts.

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -89,10 +89,11 @@ jobs:
       - run: |
           npm ci
           npm run build
-          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
+          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge ||
           # retry on failure
           if [ $? -ne 0 ]; then
-            echo "First tests attempt failed. Retrying..."
+            echo "First tests attempt failed. Retrying after 20 seconds..."
+            sleep 20
             npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
           fi
 
@@ -115,11 +116,18 @@ jobs:
         run: |
           npm ci
           npm run build
-          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
+          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge ||
           # retry on failure
           if [ $? -ne 0 ]; then
-            echo "First tests attempt failed. Retrying..."
-            npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
+            echo "First tests attempt failed. Retrying after 20 seconds..."
+            sleep 20
+            npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge ||
+            # Other OSes than linux are particularly bad on github actions, run it three times
+            if [ $? -ne 0 ]; then
+              echo "Second tests attempt failed. Retrying after 60 seconds..."
+              sleep 60
+              npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
+            fi
           fi
 
   integration_mac:
@@ -140,12 +148,21 @@ jobs:
       - run: |
           npm ci
           npm run build
-          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
-          # retry on failure
-          if [ $? -ne 0 ]; then
-            echo "First tests attempt failed. Retrying..."
-            npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge
-          fi
+          for browser in "chrome" "firefox" "edge"; do
+            npm run test:integration:$browser ||
+            # retry on failure
+            if [ $? -ne 0 ]; then
+              echo "First tests attempt failed. Retrying after 20 seconds..."
+              sleep 20
+              npm run test:integration:$browser ||
+              # Other OSes than linux are particularly bad on github actions, run it three times
+              if [ $? -ne 0 ]; then
+                echo "Second tests attempt failed. Retrying after 60 seconds..."
+                sleep 60
+                npm run test:integration:$browser
+              fi
+            fi
+          done
 
   memory_linux:
     runs-on: ubuntu-latest
